import type { KeybindingConfig } from "./types";

export const KEYBIND_CONTEXT_PREFIX = "flowquill";

const TYPABLE_KEYS = [
  ..."abcdefghijklmnopqrstuvwxyz",
  "`",
  "-",
  "=",
  "[",
  "]",
  "\\",
  ";",
  "quote",
  ",",
  ".",
  "/",
  "space",
  "tab",
  "numpad_add",
  "numpad_subtract",
] as const;

const AUTO_IGNORE_KEYS = TYPABLE_KEYS.flatMap((key) => [key, `shift+${key}`]);

const config: KeybindingConfig = {
  priority: ["global", "inspect", "interact", "change", "selectedMove", "move", "menu", "ignore"],
  modeGroups: {
    modify: ["global"],
    move: ["global", "interact", "change", "move", "ignore"],
    select: ["global", "interact", "change", "selectedMove", "ignore"],
    inspect: ["global", "inspect", "interact", "change", "move", "ignore"],
  },
  groups: {
    global: [
      { key: "escape", command: "flowquill.enterMoveMode" },
      { key: "alt+escape", command: "flowquill.enterMoveModeKeepSelection" },
      { key: "ctrl+space", command: "editor.action.triggerSuggest" },
      { key: "shift+space", command: "editor.action.inlineSuggest.commit" },
      { key: "ctrl+shift+space", command: "inlineChat.start" },
      { key: "ctrl+1", command: "workbench.view.scm" },
      {
        key: "ctrl+1",
        command: "workbench.action.toggleSidebarVisibility",
        when: "activeViewlet == 'workbench.view.scm' && sideBarFocus",
      },
      { key: "ctrl+2", command: "workbench.view.explorer" },
      {
        key: "ctrl+2",
        command: "workbench.action.toggleSidebarVisibility",
        when: "activeViewlet == 'workbench.view.explorer' && sideBarFocus",
      },
      { key: "ctrl+3", command: "workbench.panel.chat" },
      { key: "ctrl+4", command: "workbench.view.search" },
      {
        key: "ctrl+4",
        command: "workbench.action.toggleSidebarVisibility",
        when: "activeViewlet == 'workbench.view.search' && sideBarFocus",
      },
      { key: "ctrl+5", command: "timeline.focus" },
      {
        key: "ctrl+5",
        command: "workbench.action.toggleSidebarVisibility",
        when: "view.timeline.visible && activeViewlet != 'workbench.view.explorer' && sideBarFocus",
      },
      { key: "ctrl+6", command: "outline.focus" },
      {
        key: "ctrl+6",
        command: "workbench.action.toggleSidebarVisibility",
        when: "view.outline.visible && activeViewlet != 'workbench.view.explorer' && sideBarFocus",
      },
      { key: "ctrl+7", command: "workbench.view.debug" },
      {
        key: "ctrl+7",
        command: "workbench.action.toggleSidebarVisibility",
        when: "activeViewlet == 'workbench.view.debug' && sideBarFocus",
      },
      { key: "ctrl+8", command: "workbench.view.extensions" },
      {
        key: "ctrl+8",
        command: "workbench.action.toggleSidebarVisibility",
        when: "activeViewlet == 'workbench.view.extensions' && sideBarFocus",
      },
      { key: "ctrl+1", command: "-workbench.action.focusFirstEditorGroup" },
      { key: "ctrl+2", command: "-workbench.action.focusSecondEditorGroup" },
      { key: "ctrl+3", command: "-workbench.action.focusThirdEditorGroup" },
      { key: "ctrl+4", command: "-workbench.action.focusFourthEditorGroup" },
      { key: "ctrl+5", command: "-workbench.action.focusFifthEditorGroup" },
      { key: "ctrl+6", command: "-workbench.action.focusSixthEditorGroup" },
      { key: "ctrl+7", command: "-workbench.action.focusSeventhEditorGroup" },
      { key: "ctrl+8", command: "-workbench.action.focusEighthEditorGroup" },
      { key: "ctrl+9", command: "-workbench.action.lastEditorInGroup" },
      { key: "ctrl+b", command: "workbench.action.toggleSidebarVisibility" },
      { key: "ctrl+o", command: "workbench.action.togglePanel" },
      { key: "ctrl+p", command: "flowquill.window.popOutTab" },
      { key: "ctrl+alt+p", command: "flowquill.window.joinTabBack" },
      { key: "ctrl+m", command: "flowquill.window.newWindow" },
      { key: "ctrl+\\", command: "-workbench.action.splitEditor" },
      {
        key: "ctrl+shift+f",
        command: "flowquill.withCompleteSelection",
        args: { command: "workbench.action.quickTextSearch" },
      },
      { key: "ctrl+t", command: "workbench.action.showAllSymbols" },
      { key: "ctrl+s", command: "workbench.action.files.save" },
      { key: "ctrl+shift+s", command: "workbench.action.files.saveAll" },
      { key: "ctrl+r", command: "workbench.action.openRecent" },
      { key: "ctrl+g", command: "workbench.action.gotoLine" },
      { key: "ctrl+n", command: "workbench.action.files.newUntitledFile" },
      {
        key: "ctrl+tab",
        command: "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
        when: "!activeEditorGroupEmpty",
      },
      {
        key: "ctrl+tab",
        command: "workbench.action.quickOpenNavigateNextInEditorPicker",
        when: "inEditorsPicker && inQuickOpen",
      },
      {
        key: "ctrl+shift+tab",
        command: "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup",
        when: "!activeEditorGroupEmpty",
      },
      {
        key: "ctrl+shift+tab",
        command: "workbench.action.quickOpenNavigatePreviousInEditorPicker",
        when: "inEditorsPicker && inQuickOpen",
      },
      { key: "ctrl+w", command: "workbench.action.closeActiveEditor" },
      {
        key: "ctrl+enter",
        command: "flowquill.applyZenLayout",
        when: "!outline.defaultViewLocation && !timeline.defaultViewLocation",
      },
      {
        key: "ctrl+f",
        command: "flowquill.withCompleteSelection",
        args: { command: "actions.find" },
      },
      {
        key: "ctrl+alt+f",
        command: "flowquill.withCompleteSelection",
        args: { command: "editor.action.startFindReplaceAction" },
      },
      { key: "ctrl+a", command: "editor.action.selectAll" },
      { key: "f2", command: "renameFile" },
      {
        key: "tab",
        command: "-acceptSelectedSuggestion",
        when: "suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && textInputFocus",
      },
      {
        key: "tab",
        command: "-insertBestCompletion",
        when: "atEndOfWord && textInputFocus && !hasOtherSuggestions && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'",
      },
      {
        key: "tab",
        command: "-insertSnippet",
        when: "editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus && !inSnippetMode",
      },
      {
        key: "tab",
        command: "-editor.action.inlineSuggest.commit",
        when: "inlineEditIsVisible && tabShouldAcceptInlineEdit && !editorHoverFocused && !editorTabMovesFocus && !suggestWidgetVisible || inlineEditIsVisible && inlineSuggestionVisible && tabShouldAcceptInlineEdit && !editorHoverFocused && !editorTabMovesFocus && !suggestWidgetVisible || inlineSuggestionHasIndentationLessThanTabSize && inlineSuggestionVisible && !editor.hasSelection && !editorHoverFocused && !editorTabMovesFocus && !suggestWidgetVisible || inlineEditIsVisible && inlineSuggestionHasIndentationLessThanTabSize && inlineSuggestionVisible && !editor.hasSelection && !editorHoverFocused && !editorTabMovesFocus && !suggestWidgetVisible",
      },
      {
        key: "tab",
        command: "-editor.action.inlineSuggest.commit",
        when: "inInlineEditsPreviewEditor",
      },
      { key: "ctrl+d", command: "-editor.action.addSelectionToNextFindMatch", when: "editorFocus" },
      { key: "ctrl+shift+n", command: "-workbench.action.newWindow", when: "!isSessionsWindow" },
      { key: "ctrl+j", command: "-workbench.action.togglePanel" },
    ],
    inspect: [
      { key: "f", command: "flowquill.inspect.definition" },
      { key: "t", command: "flowquill.inspect.typeDefinition" },
      { key: "z", command: "flowquill.inspect.implementations" },
      { key: "g", command: "flowquill.inspect.references" },
      { key: "r", command: "flowquill.inspect.rename" },
      { key: "shift+r", command: "flowquill.inspect.renameToClipboard" },
      { key: "y", command: "flowquill.inspect.copySymbol" },
      { key: "ctrl+c", command: "flowquill.inspect.copySymbol" },
      { key: "space", command: "flowquill.inspect.quickFix" },
      { key: "e", command: "editor.action.marker.next" },
      { key: "shift+e", command: "editor.action.marker.prev" },
    ],
    interact: [
      { key: "space", command: "flowquill.enterInspectMode" },
      { key: "y", command: "flowquill.interact.copy" },
      { key: "ctrl+c", command: "flowquill.interact.copy" },
      { key: "q", command: "flowquill.macro.play" },
      { key: "shift+q", command: "flowquill.macro.toggleRecord" },
      { key: "ctrl+q", command: "flowquill.macro.load" },
      { key: "ctrl+shift+q", command: "flowquill.macro.save" },
    ],
    change: [
      { key: "i", command: "flowquill.modify.insertBefore" },
      { key: "alt+i", command: "flowquill.modify.insertBeforePreserveSelection" },
      { key: "a", command: "flowquill.modify.appendAfter" },
      { key: "alt+a", command: "flowquill.modify.appendAfterPreserveSelection" },
      { key: "shift+i", command: "flowquill.modify.insertLineStart" },
      { key: "shift+a", command: "flowquill.modify.appendLineEnd" },
      { key: "o", command: "flowquill.modify.openLineBelow" },
      { key: "shift+o", command: "flowquill.modify.openLineAbove" },
      { key: "c", command: "flowquill.modify.changeSelection" },
      { key: "ctrl+alt+c", command: "flowquill.modify.changeSelectionNoCopy" },
      { key: "r", command: "flowquill.modify.replaceChar" },
      { key: "shift+r", command: "flowquill.modify.replaceWithClipboard" },
      { key: "ctrl+shift+r", command: "flowquill.modify.replaceWithClipboardNoCopy" },
      { key: "d", command: "flowquill.modify.cut" },
      { key: "ctrl+x", command: "flowquill.modify.cut" },
      { key: "delete", command: "deleteRight" },
      { key: "backspace", command: "deleteLeft" },
      { key: "p", command: "flowquill.modify.pasteBefore" },
      { key: "shift+p", command: "flowquill.modify.pasteAfter" },
      { key: "ctrl+v", command: "flowquill.modify.pasteBefore" },
      { key: "ctrl+shift+v", command: "flowquill.modify.pasteAfter" },
      { key: "alt+p", command: "editor.action.copyLinesDownAction" },
      { key: "alt+shift+p", command: "editor.action.copyLinesUpAction" },
      { key: "tab", command: "editor.action.indentLines" },
      { key: "shift+tab", command: "editor.action.outdentLines" },
      { key: "shift+c", command: "editor.action.commentLine" },
      { key: "=", command: "editor.action.formatSelection" },
      { key: "ctrl+=", command: "flowquill.modify.toLowercase" },
      { key: "ctrl+shift+=", command: "flowquill.modify.toUppercase" },
      { key: "alt+=", command: "flowquill.modify.toggleCase" },
      { key: "u", command: "undo" },
      { key: "shift+u", command: "redo" },
      { key: ".", command: "flowquill.repeat.lastChange" },
      { key: "ctrl+j", command: "editor.action.moveLinesDownAction" },
      { key: "ctrl+down", command: "editor.action.moveLinesDownAction" },
      { key: "ctrl+k", command: "editor.action.moveLinesUpAction" },
      { key: "ctrl+up", command: "editor.action.moveLinesUpAction" },
      { key: "shift+j", command: "editor.action.joinLines" },
      { key: "-", command: "flowquill.modify.removeEmptyLines" },
      { key: "enter", command: "flowquill.modify.addLineBelow" },
      { key: "shift+enter", command: "flowquill.modify.addLineAbove" },
      { key: "alt+space", command: "flowquill.modify.addSpaceBefore" },
      { key: "alt+shift+space", command: "flowquill.modify.addSpaceAfter" },
      { key: "alt+-", command: "flowquill.select.trimWhitespace" },
      { key: "ctrl+shift+k", command: "flowquill.modify.incrementNumber" },
      { key: "alt+shift+up", command: "flowquill.modify.incrementNumber" },
      { key: "ctrl+shift+j", command: "flowquill.modify.decrementNumber" },
      { key: "alt+shift+down", command: "flowquill.modify.decrementNumber" },
      { key: "alt+shift+]", command: "flowquill.modify.rotateSelectionContentsForward" },
      { key: "alt+shift+[", command: "flowquill.modify.rotateSelectionContentsBackward" },
      { key: "z", command: "editor.toggleFold" },
      { key: ";", command: "flowquill.select.collapseToPrimary" },
      { key: "shift+;", command: "flowquill.select.switchCursorSide" },
      { key: "v", command: "flowquill.enterSelectMode" },
      { key: "m", command: "flowquill.select.matchMenu" },
      { key: "/", command: "flowquill.script.pipeExpression" },
      { key: "shift+/", command: "flowquill.script.evaluateExpression" },
      { key: "ctrl+/", command: "flowquill.script.openPipelineScript" },
      { key: "ctrl+shift+/", command: "flowquill.script.openSelectionsScript" },
      { key: "s", command: "flowquill.select.regexOrLeapForward" },
      { key: "shift+s", command: "flowquill.select.splitOrLeapBackward" },
      { key: "shift+k", command: "flowquill.select.keepByRegex" },
      { key: "shift+m", command: "flowquill.select.merge" },
      { key: "alt+s", command: "flowquill.select.splitByDelimiter" },
      { key: "quote", command: "flowquill.select.enclose" },
      { key: "alt+c", command: "flowquill.select.copySelectionDown" },
      { key: "alt+shift+c", command: "flowquill.select.copySelectionUp" },
      { key: "ctrl+shift+down", command: "flowquill.select.copySelectionDown" },
      { key: "ctrl+shift+up", command: "flowquill.select.copySelectionUp" },
    ],
    selectedMove: [
      { key: "h", command: "flowquill.select.left" },
      { key: "left", command: "flowquill.select.left" },
      { key: "j", command: "flowquill.select.down" },
      { key: "down", command: "flowquill.select.down" },
      { key: "k", command: "flowquill.select.up" },
      { key: "up", command: "flowquill.select.up" },
      { key: "l", command: "flowquill.select.right" },
      { key: "right", command: "flowquill.select.right" },
      { key: "w", command: "flowquill.select.wordForward" },
      { key: "e", command: "flowquill.select.wordEnd" },
      { key: "b", command: "flowquill.select.wordBackward" },
      { key: "shift+w", command: "flowquill.select.wordForwardBig" },
      { key: "shift+e", command: "flowquill.select.wordEndBig" },
      { key: "shift+b", command: "flowquill.select.wordBackwardBig" },
      { key: "x", command: "flowquill.select.lineDown" },
      { key: "shift+x", command: "flowquill.select.lineUp" },
      { key: "ctrl+h", command: "flowquill.select.lineStart" },
      { key: "ctrl+left", command: "flowquill.select.lineStart" },
      { key: "ctrl+l", command: "flowquill.select.lineEnd" },
      { key: "ctrl+right", command: "flowquill.select.lineEnd" },
      { key: "ctrl+d", command: "flowquill.select.halfPageDown" },
      { key: "ctrl+shift+u", command: "flowquill.select.halfPageDown" },
      { key: "ctrl+u", command: "flowquill.select.halfPageUp" },
      { key: "ctrl+shift+d", command: "flowquill.select.halfPageUp" },
      { key: "alt+h", command: "flowquill.select.left" },
      { key: "alt+j", command: "flowquill.select.down" },
      { key: "alt+k", command: "flowquill.select.up" },
      { key: "alt+l", command: "flowquill.select.right" },
      { key: "alt+w", command: "flowquill.select.wordForward" },
      { key: "alt+e", command: "flowquill.select.wordEnd" },
      { key: "alt+b", command: "flowquill.select.wordBackward" },
      { key: "f", command: "flowquill.select.findCharForward" },
      { key: "t", command: "flowquill.select.tillCharForward" },
      { key: "shift+f", command: "flowquill.select.findCharBackward" },
      { key: "shift+t", command: "flowquill.select.tillCharBackward" },
      { key: "n", command: "flowquill.select.nextOccurrence" },
      { key: "shift+n", command: "flowquill.select.previousOccurrence" },
    ],
    move: [
      { key: "h", command: "flowquill.move.left" },
      { key: "left", command: "flowquill.move.left" },
      { key: "j", command: "flowquill.move.down" },
      { key: "down", command: "flowquill.move.down" },
      { key: "k", command: "flowquill.move.up" },
      { key: "up", command: "flowquill.move.up" },
      { key: "l", command: "flowquill.move.right" },
      { key: "right", command: "flowquill.move.right" },
      { key: "w", command: "flowquill.move.wordForward" },
      { key: "e", command: "flowquill.move.wordEnd" },
      { key: "b", command: "flowquill.move.wordBackward" },
      { key: "shift+w", command: "flowquill.move.wordForwardBig" },
      { key: "shift+e", command: "flowquill.move.wordEndBig" },
      { key: "shift+b", command: "flowquill.move.wordBackwardBig" },
      { key: "x", command: "flowquill.select.lineDown" },
      { key: "shift+x", command: "flowquill.select.lineUp" },
      { key: "ctrl+h", command: "flowquill.move.lineStart" },
      { key: "ctrl+left", command: "flowquill.move.lineStart" },
      { key: "ctrl+l", command: "flowquill.move.lineEnd" },
      { key: "ctrl+right", command: "flowquill.move.lineEnd" },
      { key: "ctrl+alt+h", command: "flowquill.select.lineStart" },
      { key: "ctrl+alt+left", command: "flowquill.select.lineStart" },
      { key: "ctrl+alt+l", command: "flowquill.select.lineEnd" },
      { key: "ctrl+alt+right", command: "flowquill.select.lineEnd" },
      { key: "g", command: "flowquill.move.grabWord" },
      { key: "shift+g", command: "flowquill.move.grabWordBig" },
      { key: "f", command: "flowquill.move.findCharForward" },
      { key: "t", command: "flowquill.move.tillCharForward" },
      { key: "shift+f", command: "flowquill.move.findCharBackward" },
      { key: "shift+t", command: "flowquill.move.tillCharBackward" },
      { key: "alt+f", command: "flowquill.select.findCharForward" },
      { key: "alt+shift+f", command: "flowquill.select.findCharBackward" },
      { key: "alt+t", command: "flowquill.select.tillCharForward" },
      { key: "alt+shift+t", command: "flowquill.select.tillCharBackward" },
      { key: "ctrl+d", command: "flowquill.move.halfPageDown" },
      { key: "ctrl+shift+u", command: "flowquill.move.halfPageDown" },
      { key: "ctrl+u", command: "flowquill.move.halfPageUp" },
      { key: "ctrl+shift+d", command: "flowquill.move.halfPageUp" },
      { key: "ctrl+alt+d", command: "flowquill.select.halfPageDown" },
      { key: "ctrl+alt+shift+u", command: "flowquill.select.halfPageDown" },
      { key: "ctrl+alt+u", command: "flowquill.select.halfPageUp" },
      { key: "ctrl+alt+shift+d", command: "flowquill.select.halfPageUp" },
      { key: "alt+h", command: "flowquill.select.left" },
      { key: "alt+j", command: "flowquill.select.down" },
      { key: "alt+k", command: "flowquill.select.up" },
      { key: "alt+l", command: "flowquill.select.right" },
      { key: "alt+w", command: "flowquill.select.wordForward" },
      { key: "alt+e", command: "flowquill.select.wordEnd" },
      { key: "alt+b", command: "flowquill.select.wordBackward" },
      { key: "alt+n", command: "flowquill.select.nextOccurrence" },
      { key: "alt+shift+n", command: "flowquill.select.previousOccurrence" },
      { key: "n", command: "flowquill.move.searchNext" },
      { key: "shift+n", command: "flowquill.move.searchPrevious" },
      { key: "[", command: "flowquill.move.jumpBack", when: "canNavigateBack" },
      { key: "]", command: "flowquill.move.jumpForward", when: "canNavigateForward" },
      { key: "oem_4", command: "flowquill.move.jumpBack", when: "canNavigateBack" },
      { key: "oem_6", command: "flowquill.move.jumpForward", when: "canNavigateForward" },
    ],
    ignore: AUTO_IGNORE_KEYS.map((key) => ({
      key,
      command: "flowquill.ignore",
    })),
    menu: [
      { key: "h", command: "list.collapse", when: "listFocus && !inputFocus" },
      { key: "j", command: "list.focusDown", when: "listFocus && !inputFocus" },
      { key: "k", command: "list.focusUp", when: "listFocus && !inputFocus" },
      { key: "l", command: "list.expand", when: "listFocus && !inputFocus" },
      { key: "a", command: "explorer.newFile", when: "filesExplorerFocus && listFocus && !inputFocus" },
      { key: "shift+a", command: "explorer.newFolder", when: "filesExplorerFocus && listFocus && !inputFocus" },
      { key: "r", command: "renameFile", when: "filesExplorerFocus && listFocus && !inputFocus" },
    ],
  },
};

export default config;
